path_dataset: './data/'
path_models: ''
path_results: './out/results/'

# Override to point at the MP3D dataset built from the H5.
path_episodes_root: "/data/ws/VLN-CE/controller/object_react/eval/dataset/mp3d_iin_test"
#'/data/ws/VLN-CE/controller/object_react/eval/data/mp3d_iin_test'
path_scenes_root: '/data/dataset/RXR/dataset/mp3d/data/scene_datasets/mp3d/v1/tasks/mp3d_habitat/mp3d'
scene_dataset: 'mp3d'

# episode/task settings
start_idx: 0
step_idx: 1
end_idx: -1

reverse: False
task_type: "original"
use_gt_localization: True
env: "sim"

split: "test"
threshold_goal_distance: 1.0
max_start_distance: "hard"
max_steps: 300

exp_name: "lang_mp3d_eval"

run_list: ''
path_run: ''

# controller and mapping params
method: "learnt" #['learnt', "disabled"] 
segmentor: 'fast_sam'
goal_source: 'lang_e3d'
graph_filename: null
infer_depth: False
infer_traversable: False

# lang_e3d-specific
joint_checkpoint: "/data/ws/VLN-CE/controller/object_react/train/logs/e3d_object_react/joint_train_2026_04_30_01_43_45_/joint_latest.pth"
#"/data/ws/VLN-CE/controller/object_react/train/logs/e3d_object_react/joint_train_2026_04_30_01_43_45_/joint_latest.pth" 
#'/data/ws/VLN-CE/controller/object_react/train/checkpoints/joint/best_joint_190426_episodic_inst.pth'
#/data/ws/VLN-CE/controller/object_react/train/logs/e3d_object_react/joint_train_2026_04_23_10_35_23_/joint_latest.pth #
instruction_type: "episodic"   # "episodic" | "next_action"

# logging and display
log_wandb: False
log_robot: True
debug: False
except_exit: False

plot: False
save_vis: False

cull_qry_instances: False
cull_map_instances: False

sim:
  hfov: 120
  width: 320
  height: 240
  sensor_height: 0.4
  sensor_height_map: 1.31

goal_gen:
  textLabels: []
  map_segmentor_name: "fast_sam"
  matcher_name: "lightglue"
  map_matcher_name: "lightglue"
  geometric_verification: True
  match_area: False
  edge_weight_str: "e3d"
  goalNodeIdx: null
  use_goal_nbrs: False
  plan_da_nbrs: False
  preplan_to_goals_only: False
  rewrite_graph_with_allPathLengths: False
  loc_radius: 16
  subsample_ref: 2

controller:
  config_file: "configs/controller/object_react_controller.yaml"
  v_min: 0.05
  v_max: 0.40
  w_min: -0.5
  w_max: 0.5
